### ISSUE TITLE
Feature request: RejectFailures should not apply to quarantine

### ISSUE THREAD

**Issue by tomsommer** [trusteddomainproject/OpenDMARC#77]
`RejectFailures` results in a milter-hold on `p=quarantine`. This is very often not desirable. It would be great if one could make `RejectFailures` not apply to `p=quarantine`, perhaps with a setting on its own that controls the behavior.

**Comment by juh** [comment]
It would be great, if those responsible for this project would move the issues from the old project site at SourceForge to GitHub, as this issue was already reported and a patch submitted. See https://sourceforge.net/p/opendmarc/tickets/138/.
Unfortunately the discussion in this ticket went to another subject (displaying the disposition state of the message in the headers), which was implemented and then the ticket closed. The original issue (mails from domains with p=quarentine go the hold queue) was not solved and the mentioned patch is still needed.

**Comment by celesteking** [comment]
I just checked and I like like how it's been implemented. It returns `SMFIR_QUARANTINE` modaction along with `SMFIR_ACCEPT` disposition action in case of `p=quarantine`. It returns `SMFIR_REPLYCODE` with a nice reason (instead of just `REJECT` -- thanks!) in case of `p=reject`.  I don't see any problem here, really. 

The only problem is with your side (MTA) and that should be fixed/complained/brought up there.

**Comment by thegushi** [comment]
Tomsommer: I'm in the process of triaging some old tickets -- can you tell me which MTA you're using and how you're calling the milter?  

If I understand correctly, your MTA has a quarantine function, and it's using it when the milter says to do so, and what you'd like to have happen is instead, have opendmarc return a response that lets the message still get delivered, but [perhaps] some later element in the chain, like SpamAssassin act on the message instead.

Do I grok?

**Comment by justinclloyd** [comment]
@thegushi I'm not Tom, but I've seen this same problem on my Postfix 3.1 Ubuntu 16.04 servers (which I do plan to update to 20.04 soon-ish), which is why I've been watching this issue. I'd only implemented SPF, DKIM, and DMARC a few months ago and suddenly saw occasional messages getting stuck in the hold queue thanks to monitoring the queues in a Grafana dashboard. Took me a little while to figure out that it was this OpenDMARC setting causing it.

**Comment by tomsommer** [comment]
Using Postfix, yes. Exactly what @justinclloyd is describing.

**Comment by thegushi** [comment]
This ticket may close when that's merged.

**Comment by martinbogo** [comment]
Tis merged, closing issue.

-Martin

**Comment by celesteking** [comment]
It looks like you have changed the behavior with this patch. It should've remained at old setting instead of breaking peoples' config.
